### ISSUE TITLE
Prune Unnecessary Calls

### ISSUE THREAD

**Issue by qrealm** [obryanlouis/4pchess#17]
The idea is you don't need to call the see function if the piece being captured is a queen or lower and the capturing piece is a pawn. The value is obviously positive.
1. **Prune Based on Cumulative Value**: If at any point the cumulative SEE value becomes highly positive or negative, you can stop the evaluation. For example, if the value is very negative, it implies that the captures are heavily favoring one side, and further captures are unlikely to change the result.
2. **Prune After First Recapture**: This is an aggressive optimization. After the first piece is captured (i.e., the first recursive SEE call), if the result is positive (favorable trade), stop the SEE.
3. **Use an Absolute Value Threshold**: If the SEE value, at any point, goes below or exceeds a certain threshold, stop the evaluation.

**Comment by qrealm** [comment]
Here is a example on how it's implemented.
```cpp
int Search::see(Position pos, int square) {
    const int color = pos->color;
    std::pair<int, int> piece = pos->getSmallestAttacker(square, color);
    if (piece.first == -1) {
        return 0;
    }
    int attackerValue = MATERIAL_SCORES[piece.first];
    int capturedPieceValue = MATERIAL_SCORES[pieMB[square]];
    // Lazy Evaluation.
    if (attackerValue > capturedPieceValue) {
        return -attackerValue;
    }
    Move captureMove{ piece.second, square, NO_PIECE, CAPTURE, piece.first, pieMB[square], colMB[square], -1 };
    History history = pos->move(captureMove);
    // Prune after the first recapture.
    int recursiveValue = see(pos, square);
    if (recursiveValue > 0) {
        pos->undo(history, captureMove);
        return capturedPieceValue;
    }
    // Prune based on cumulative value or absolute threshold.
    int seeValue = capturedPieceValue - recursiveValue;
    if (seeValue < -SEE_THRESHOLD || seeValue > SEE_THRESHOLD) {
        pos->undo(history, captureMove);
        return seeValue;
    }
    pos->undo(history, captureMove);
    return std::min(capturedPieceValue, seeValue);
}
```
Remember to choose your thresholds wisely. Too aggressive pruning can degrade the accuracy of the SEE and negatively affect the engine's performance. Always test the effects of any SEE optimizations using a suite of test positions and games to ensure there are no regressions.

**Comment by obryanlouis** [comment]
Thanks for the suggestion! I tested the first one and think it would work well. Closing as this will be added in a future commit.
