### ISSUE TITLE
Lazy Evaluation

### ISSUE THREAD

**Issue by user-error-pixel** [obryanlouis/4pchess#6]
When the engine is above a certain eval then preform lazy evaluation to improve the speed of the search algo.
https://www.chessprogramming.org/Lazy_Evaluation
Here is a way it could be implemented.
```c++
int eval;
// Lazy Evaluation
if (alpha > LAZY_EVAL_THRESHOLD) {
    eval = pos.evalLazy();
} else {
    eval = pos.evalFull();
}
```

**Comment by obryanlouis** [comment]
The engine has lazy eval now. Thanks for the suggestion!
Lazy eval helps increase the NPS a bit (IIRC, 240k -> 310k NPS)
